//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public string CommentID { get; set; }
        public string CommentText { get; set; }
        public string UserName { get; set; }
        public System.DateTime CommentDate { get; set; }
        public string ParentID { get; set; }
    
        public virtual MarketingCoordinator MarketingCoordinator { get; set; }
        public virtual Student Student { get; set; }
    }
}
