//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public string ContentID { get; set; }
        public string ContentName { get; set; }
        public string ContentDescription { get; set; }
        public string UserName { get; set; }
    }
}
