//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTent
    {
        public string CTID { get; set; }
        public string CTname { get; set; }
        public string CTDescription { get; set; }
        public string CTTag { get; set; }
    }
}
