//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class MarketingCoordinator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MarketingCoordinator()
        {
            this.ContentAssigns = new HashSet<ContentAssign>();
        }
        [DisplayName("ID")]
        [Required(ErrorMessage = "Field can't be empty")]
        public string MCID { get; set; }
        [DisplayName("MC")]
        [Required(ErrorMessage = "Field can't be empty")]
        public string MCName { get; set; }
        [DisplayName("Address")]
        public string MCAddress { get; set; }
        [DisplayName("Phone")]
        public string MCPhone { get; set; }
        [DisplayName("Faculty")]
        public Nullable<int> FacultyID { get; set; }
        public string UserName { get; set; }
        [DisplayName("Email")]
        [Required(ErrorMessage = "Field can't be empty")]
        [DataType(DataType.EmailAddress, ErrorMessage = "E-mail is not valid")]

        public string MCEmail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContentAssign> ContentAssigns { get; set; }
        public virtual Faculty Faculty { get; set; }
    }
}
