//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class MarketingManager
    {
        [DisplayName("ID")]
     
        public string MMID { get; set; }
        [DisplayName("Name")]
       
        public string MMName { get; set; }
        [DisplayName("Address")]
        public string MMAddress { get; set; }
        [DisplayName("Email")]
       
        [DataType(DataType.EmailAddress, ErrorMessage = "E-mail is not valid")]
        public string MMEmail { get; set; }
        [DisplayName("Phone")]
        public string MMPhone { get; set; }
     
        public string UserName { get; set; }
    }
}
