//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketingCoordinator
    {
        public string MCID { get; set; }
        public string MCName { get; set; }
        public string MCAddress { get; set; }
        public string MCPhone { get; set; }
        public string CTTag { get; set; }
    
        public virtual ConTent ConTent { get; set; }
        public virtual CTTag CTTag1 { get; set; }
    }
}
