//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reply
    {
        public string ReplyID { get; set; }
        public string StudentID { get; set; }
        public string MCID { get; set; }
        public string CommentID { get; set; }
        public string Reply1 { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual MarketingCoordinator MarketingCoordinator { get; set; }
        public virtual Student Student { get; set; }
    }
}
